<a href="https://colab.research.google.com/github/zzickso/python_lecture/blob/main/%ED%8C%8C%EC%9D%B4%EC%8D%AC_%EA%B8%B0%EC%B4%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
#enumerate
num=[2,4,6,8,10,12,14]
for i,n in enumerate(num):
    num[i]=n*13
    print(num)

[26, 4, 6, 8, 10, 12, 14]
[26, 52, 6, 8, 10, 12, 14]
[26, 52, 78, 8, 10, 12, 14]
[26, 52, 78, 104, 10, 12, 14]
[26, 52, 78, 104, 130, 12, 14]
[26, 52, 78, 104, 130, 156, 14]
[26, 52, 78, 104, 130, 156, 182]


In [72]:
#행렬
import numpy as np

x= np.array([[1,2,3],[4,5,6],[1,2,3,],[1,1,1]])
print(x)
x.shape #행렬의 크기

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [1 1 1]]


(4, 3)

In [38]:
a= np.array([1,1,1])
b= a.copy() #ndarray형의 복사
print('a='+ str(a))
print(b)
b[0]=100 #요소의 수정
print(b)
print(a)

a=[1 1 1]
[1 1 1]
[100   1   1]
[1 1 1]


In [39]:
#연속된 정수 벡터의 생성
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
x = np.array([[1,2,3],[4,5,6]])
x[0,0]=100
x

array([[100,   2,   3],
       [  4,   5,   6]])

In [47]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [49]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [50]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [51]:
#요소가 랜덤인 행렬
#각 요소는 0~1 균일한 분포 행렬 형태로 생성함
#np.random.randn(siez) 평균0 분산 1의 가우스 분포로 난수 생성
np.random.rand(2,3)

array([[0.74789713, 0.76818232, 0.23164295],
       [0.54515609, 0.89355127, 0.49549967]])

In [71]:
#행렬의 크기 변경
x= np.array([[1,2,3],[4,5,6],[1,2,3,]])
x
x.reshape(9,)

array([1, 2, 3, 4, 5, 6, 1, 2, 3])

In [74]:
#행렬의 사칙연산
x=np.array([[4,4,4],[8,8,7]])
y=np.array([[1,2,3],[4,5,6]])
print(x+y)

[[ 5  6  7]
 [12 13 13]]


In [75]:
x=np.array([[4,4,4],[8,8,7]])
y=np.array([[1,2,3],[4,5,6]])
print(x*y)

[[ 4  8 12]
 [32 40 42]]


In [76]:
x=np.array([[4,4,4],[8,8,7]])
y=np.array([[1,2,3],[4,5,6]])
print(10*x,y)

[[40 40 40]
 [80 80 70]] [[1 2 3]
 [4 5 6]]


In [77]:
#산술 함수
x=np.array([[4,4,4],[8,8,7]])
np.exp(x)

array([[  54.59815003,   54.59815003,   54.59815003],
       [2980.95798704, 2980.95798704, 1096.63315843]])

In [84]:
#행렬 곱의 계산
x=np.array([[4,4,4],[8,8,7]])
y=np.array([[1,2],[5,6],[2,2]])
print(x.dot(y))

x=np.array([[4,4,4],[8,8,7]])
y=np.array([[2,2],[5,6],[2,2]])
print(x.dot(y))

x=np.array([[4,4,4],[8,8,7]])
y=np.array([[3,2],[5,6],[2,2]])
print(x.dot(y))

[[32 40]
 [62 78]]
[[36 40]
 [70 78]]
[[40 40]
 [78 78]]


In [91]:
#슬라이싱(참조)
x=np.arange(10)
print(x)
print(x[:5]) # :n

# n:
print(x[5:])

#[n1:n2:dn]-----n2-n1 범위에서 dn간격
print(x[3:8:2])
print(x[3:7:2])
print(x[3:10:1])


[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[5 6 7 8 9]
[3 5 7]
[3 5]
[3 4 5 6 7 8 9]


In [100]:
# bool 배열 사용
x=np.array([1,1,2,3,5,5,8,13])
x>3

array([False, False, False, False,  True,  True,  True,  True])

In [101]:
x[x>3]

array([ 5,  5,  8, 13])

In [102]:
x[x>3]=999
print(x)

[  1   1   2   3 999 999 999 999]


In [103]:
#help 사용
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the ``integers`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distributi

In [104]:
#함수
def my_func1():
    print('Hi')
my_func1

<function __main__.my_func1>

In [108]:
def my_func2(a,b):
    c= a+b
    return c

my_func2(1,2)

3

In [115]:
def my_func3(D):
    m=np.mean(D)
    s=np.std(D)
    return m,s

data=np.random.randn(100)
data_mean,data_std=my_func3(data)
print('mean:{0:3.2f},std:{1:3.2f}'.format(data_mean,data_std))

mean:0.02,std:0.99


In [116]:
#파일 저장
data= np.random.randn(5)
print(data)
np.save('datafile.npy', data) #세이브
data=[] #데이터 삭제
print(data)
data=np.load('datafile.npy') #로드
print(data)

[ 1.19317012 -0.53741071  0.40968409 -1.3885558   0.25644573]
[]
[ 1.19317012 -0.53741071  0.40968409 -1.3885558   0.25644573]


In [117]:
#여려 ndarray 형을 저장
data1= np.array([1,2,3])
data2= np.array([10,20,30])
np.savez('datafile2.npz',data1=data1, data2=data2) #세이브
data1=[] #데이터 삭제
data2=[]
outfile=np.load('datafile2.npz') #로드
print(outfile.files) #저장된 데이터 표시
data1= outfile['data1']#data1 꺼내기
data2= outfile['data2']#data2 꺼내기
print(data1)
print(data2)

['data1', 'data2']
[1 2 3]
[10 20 30]
